### ISSUE TITLE
What was it like to learn Racket?

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/racket#130]
We’ve recently [started a project](https://exercism.io/blog/redesigning-tracks-in-partnership-with-chicago-university-and-sloan-foundation) to find the best way to design our tracks, in order to optimize the learning experience of students.

As a first step, we’ll be [examining the ways in which languages are unique and the ways in which they are similar](https://github.com/exercism/exercism/issues/5059). For this, we’d really like to use the knowledge of **everyone** involved in the Exercism community (students, mentors, maintainers) to answer the following questions:

1. How was your experience learning Racket? What was helpful while learning Racket? What did you struggle with? How did you tackle problems?
1. In what ways did Racket differ from other languages you knew at the time? What was hard to learn? What did you have to unlearn? What syntax did you have to remap? What concepts carried over nicely?

Could you spare 5 minutes to help us by answering these questions? It would greatly help us improve the experience students have learning Racket :)

_Note: this issue is **not** meant as a discussion, just as a place for people to post their own, personal experiences._

_Want to keep your thoughts private but still help? Feel free to email me at erik@exercism.io_

Thank you!

**Comment by zkry** [comment]
In my mind, here are some things that, for example, a Go developer might find different:
- Syntax: A lot of people see the s-expression syntax as a big obstacle.
- Functional Programming and all that entails
- "Vocabulary size": Racket is a really large, powerful language. Just the package importing/exporting is a DSL that takes a little time to learn. Looking at the documentation there is over 30 variations of "for" loops (ex. `for`, `for/list`, `for*/product`).
- Meta programming: https://docs.racket-lang.org/reference/Macros.html

The documentation at docs.racket-lang.org was extremely helpful. Unfortunately, Stack Overflow wasn't that helpful as Racket isn't isn't that widely used.

One of the biggest struggles I had when trying to learn Racket was it's macro system. Normally a languages macro system might be brushed off, to be learned after mastering the language. Racket however, is labeled as a Language-oriented programming ecosystem.

I tried to take this idea to heart when working on some of the exercises. It didn't really fit the exercises well but here are the examples:

Scrabble: https://exercism.io/tracks/racket/exercises/scrabble-score/solutions/09c084b8e31f48f3b91c381fbf407815 

Raindrops: https://exercism.io/tracks/racket/exercises/raindrops/solutions/222946fc70f64eb3a23382d7dc2296a4

It would be really helpful if there were some domain specific language related exercises.

On a side note, it seemed like there wasn't many mentors active. Hopefully that can change though.

**Comment by cousinitt** [comment]
Racket was my first Lisp-y language. Originally, I wasn't interested in Racket, but in Scheme. That quickly changed when I downloaded DrRacket. The documentation that comes with it is great, the mailing list is active and friendly, and there is quite a lot of information out on the internet for learning Racket. While it is sold as a language to teach, it is a surprisingly well designed and mature language.

The Exercism Racket track was very helpful to me. The mentor feedback pointed me in directions for better code, and better utilization of what was already available in Racket. Sadly, I am sort of a "good enough" person, having a mentor remind me helps me get out of that habit. Just because it is an exercise doesn't mean that I shouldn't make the submission as good as I can make it.

I would echo @zkry's thoughts about macros, DSLs, contracts, etc.

I still feel like I have a lot to learn from Racket, but these things have helped me along my journey:
Scheme-y programming (in no particular order):
[How to Design Programs](https://htdp.org)
[The Racket Guide](https://docs.racket-lang.org/guide/index.html)
[Realm of Racket](https://nostarch.com/realmofracket.htm)
[The Little Schemer](https://mitpress.mit.edu/books/little-schemer-fourth-edition)
[The Scheme Programming Language](https://www.scheme.com/tspl4/)
[Teach Yourself Scheme in Fixnum Days](http://ds26gte.github.io/tyscheme/index.html)

Macros:
[Fear of Macros](https://www.greghendershott.com/fear-of-macros/)
[JRM's Syntax-rules Primer for the Merely Eccentric](https://hipster.home.xs4all.nl/lib/scheme/gauche/define-syntax-primer.txt)

DSLs:
[Beautiful Racket](https://beautifulracket.com)

**Comment by ErikSchierboom** [comment]
We're closing this issue as it was part of our research for the v3 version of Exercism which has [just been released](https://exercism.org/blog/exercism-v3-has-launched).

Thanks everyone for chipping in! It has been greatly appreciated.
